### ISSUE TITLE
Implementing JBrowse 2 checklist

### ISSUE THREAD

**Issue by scottcain** [WormBase/website-genome-browsers#182]
- [x] convert remaining tracks configs.
- [x] merge existing code into stage (putting JBrowse embedded in location widget, and "demo"/beta implementation of synteny browser)
- [x] big issue: transition GBrowse_syn (separate checklist: [#183](https://github.com/WormBase/website-genome-browsers/issues/183))
- [x] update website links to GBrowse to point at JBrowse 2
- [x] create wormbase specific user tutorial

Not exactly related to retiring GBrowse, but needs to be done eventually (ie, these are lowest priority):
- [ ] Port sequence feature widget
- [ ] Port protein "homology" widget

**Comment by scottcain** [comment]
All of the tracks have been ported but one that I found while doing other things, because it is no longer included in JBrowse 1 for reasons that are not clear to me (see https://github.com/WormBase/website/issues/7406)
